# Generated by Django 2.2.1 on 2019-05-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='group',
            field=models.ManyToManyField(related_name='Works', to='server.Group'),
        ),
    ]
